### ISSUE TITLE
Publish to Play Store 

### ISSUE THREAD

**Issue by xmha97** [warren-bank/Android-Mock-Location#10]
Please add this app to Play Store

**Comment by warren-bank** [comment]
None of my app are published to any 3rd-party marketplace. All official releases are available directly from the original repo(s).

1. dealing with these 3rd parties is a time-consuming headache
2. I see no benefit to either myself or the end user.. only the 3rd-party marketplace(s)
3. doing so promotes the proliferation of walled-gardens.. which are everywhere these days.. and they're evil
