### ISSUE TITLE
No matching configuration of project

### ISSUE THREAD

**Issue by Volkovx19** [warren-bank/Android-Mock-Location#17]
No matching configuration of project :Mock-my-GPS-UnifiedNlp-Backend-artifacts was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:languageResources' with value 'english', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.1.1' but:

**Comment by warren-bank** [comment]
oh, f*ck me..

* the [`libs` directory is included in .gitignore](
https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.03.01/.gitignore#L10
)
* the [`libs` directory is the root of a project](
https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.03.01/android-studio-project/settings.gradle#L5
)

I'll need to see if I still have a local copy of the source that includes
this `libs` directory.

**Comment by warren-bank** [comment]
oh, f*ck me..

* the [`libs` directory is included in .gitignore](https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.03.01/.gitignore#L10)
* the [`libs` directory is the root of a project](https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.03.01/android-studio-project/settings.gradle#L5)

I'll need to see if I still have a local copy of the source that includes this `libs` directory.

**Comment by warren-bank** [comment]
no local backup.. so I [rewrote the missing code](https://github.com/warren-bank/Android-Mock-Location/commit/b4af4e9b9651d2be8330149203bb6f7c612db848)

to test, I..
* decompiled the APKs for the [most recent release](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.03.01)
* decompiled the APKs built using this new code
* compared the outputs
* no difference

thanks for letting me know that there was a problem..
I can't believe that I did that (sigh)
