### ISSUE TITLE
App crashes when setting location

### ISSUE THREAD

**Issue by m0yP** [warren-bank/Android-Mock-Location#2]
When setting location it just crashes.

Here's the log https://del.dog/nuricuckul 

I'm running Android 10 and have enabled  Developer Settings and have included the app under the "select mock location app".

**Comment by warren-bank** [comment]
That security policy was added in [Android 9](https://developer.android.com/about/versions/pie/android-9.0-migration#tya)

I need to add a line to [`AndroidManifest.xml`](https://github.com/warren-bank/Android-Mock-Location/blob/service/android-studio-project/Mock-my-GPS/src/main/AndroidManifest.xml):
```xml
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

Thanks for the heads up.. none of my devices are new enough to remind me that I needed to apply updates. Really wish Android devs would stop making breaking changes in userland.

I'll push an update either tonight or early tomorrow.

**Comment by m0yP** [comment]
Thanks!

**Comment by warren-bank** [comment]
ok. Please give [v2.1.6](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.01.06) a try and let me know if that fixes/prevents the crash.

- - - -

On an unrelated note.. another thing that I should update is the way the joystick is displayed on API 26+ (Android 8.0). On older versions of Android, the joystick could be long-clicked and dragged to move its position. The layout it used was no-longer allowed and caused the app to crash.. so I made a change that fixes/prevents _that_ crash.. but lost some of its functionality. I think I may investigate that a little tonight..

__update__:<br>I was wrong.. the drag functionality actually does still work; it's just really hard to use. It's not activated by long click at all. It basically treats anywhere in its layout that isn't a button as a drag handle: touch, drag, release. The trouble is that the only unused space in the layout are the transparent corners adjacent to the buttons.. which is __not__ intuitive. So, it's an issue of bad UI; easy enough to fix.. just need to think about a better UI solution.

__update__:<br>[v2.1.7](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.01.07) updates the UI by giving the joystick a drag-handle (at its center).

**Comment by m0yP** [comment]
Awesome! It works now out of the box. And joystick works ok too. Thanks for the quick response.
