### ISSUE TITLE
App specification

### ISSUE THREAD

**Issue by NiX3r** [warren-bank/Android-Mock-Location#20]
# Hi there 👋 
is there way to set specific app (app ID, PID, etc.) to show fake GPS?

## My use of case
I'm using DJI drone and want to disable NFZ (no-fly-zone) and altitude limits. This could be possible to fake my GPS to random location in the USA. However I'm also using ATAK - which is basically military apps to share data such as position, images or in my case drone view and location. So I need to fake GPS only in DJI Fly app and show real GPS in ATAK

**Comment by warren-bank** [comment]
To the best of my knowledge, Android only enables or disables location mocking at a system-wide level. Sorry.

**Comment by NiX3r** [comment]
Sad to hear. Anyway, thanks for your pretty quick answer 💪
