### ISSUE TITLE
can not mock alipay miniprograms

### ISSUE THREAD

**Issue by mahengrui1** [warren-bank/Android-Mock-Location#22]
it works at Amap but fails at some miniprograms in Alipay (these are in Chinese language)

**Comment by Lambda-zhou** [comment]
it seems like it cannot work on tencents app, so 还是fakelocation吧

**Comment by warren-bank** [comment]
Hi all. Sorry for the late reply. I just googled the issue to find more information. Here is what I found..

* [stackoverflow discussion](https://stackoverflow.com/questions/37175039/how-does-some-appswechat-ignore-fake-location-and-then-detect-the-real-one)
* [techjunkie article](https://social.techjunkie.com/change-location-in-wechat/)

To summarize: `BaiduLocationSDK` bypasses Android APIs and directly queries the GPS hardware at a much lower level. Any app that uses this library to obtain GPS location cannot be mocked.

PS: it's also interesting to note that this library ignores whether or not GPS is turned off in Android's Settings. It'll use the GPS hardware regardless.

**Comment by warren-bank** [comment]
[This article](https://digitalcreative.cn/blog/location-service-packages-china-app-development) is very informative. It lists and then describes in great detail each of the major location-related libraries for use in China.

* [Amap Developer Platform (高德地图)](http://lbs.amap.com/)
  - AMap, also known as Gaode Maps, is provided by AutoNavi, a subsidiary of Alibaba Group
* [Baidu Location Services (百度地图)](http://lbsyun.baidu.com/)
  - Baidu Maps is one of the leading location service providers in China
  - Social apps like WeChat and Momo use Baidu's location features
* [Tencent Location Services](https://lbs.qq.com/)
  - the tech conglomerate behind WeChat, QQ, Tencent Maps, and other popular apps
* [Huawei Developer Platform](https://developer.huawei.com/consumer/en/hms/huawei-locationkit/)
  - Huawei, the leading Chinese tech giant, provides its own location services
* [Here WeGo (和图地图)](https://developer.here.com/)
  - initially a Nokia service, Here WeGo has been adapted for the Chinese market under the name 和图地图 (Hetu Maps)
* [Mapbox China](https://docs.mapbox.com/api/overview/)
* [NavInfo Location Services](https://www.navinfo.eu/about-us/)
* [UniStrong Location Services](http://en.unistrong.com/)

**Comment by mahengrui1** [comment]
> PS: it's also interesting to note that this library ignores whether or not GPS is turned off in Android's Settings. It'll use the GPS hardware regardless.

@warren-bank Hello the owner, thank you for the information. Besides, when you mention this, do you say it uses base station positioning(calculated by determining how far way it is from the base stations forming the carrier network) instead of Global Navigation Satellite System? As this is an explanation sounds more familiar with.

**Comment by warren-bank** [comment]
Though I don't have any more information than what I gathered from a quick read of the pages that I previously linked to,
I would assume that the methodology used by some of these libraries is similar to:

* https://gist.github.com/kanru/1568934
* https://github.com/Vagr9K/GPSTester

**Comment by mahengrui1** [comment]
Thank you, should the issue closed as completed or not planned?
