### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [warren-bank/Android-Mock-Location#26]
I use the browser to test the location, Not working app
https://mylocation.org
https://browserleaks.com/geo
https://www.where-am-i.net
https://www.michaelhorowitz.com/location.tester.php

My device: Google Pixel7
System: GrapheneOS

**Comment by warren-bank** [comment]
did you..

1. set this app as the "mock location app"? ..in Android settings > developer options
2. start the location mocking service (in the app)

note that when working properly:

* the JS location API will correctly report the mocked location
* your public IP address is unchanged.. so a rough approximation of your real location is still possible when you make requests to a server

**Comment by ghost** [comment]
[](url)

> did you..
> 
> 1. set this app as the "mock location app"? ..in Android settings > developer options

Sorry, I didn't set it.

> 2. start the location mocking service (in the app)
> 
> note that when working properly:
> 
> * the JS location API will correctly report the mocked location
> * your public IP address is unchanged.. so a rough approximation of your real location is still possible when you make requests to a server
