### ISSUE TITLE
Ability to specify a location on the map

### ISSUE THREAD

**Issue by Korb** [warren-bank/Android-Mock-Location#27]
This way, the user will generally not need to use two applications instead of one.

**Comment by warren-bank** [comment]
I stand by [what I said](https://github.com/warren-bank/Android-Mock-Location#design-goals). Sounds like you might prefer the UI in [FakeTraveler](https://github.com/mcastillof/FakeTraveler). It's a great app with this particular feature. Personally, I prefer apps that try to do one thing.. and do them really well; imho, a map UI is better handled by an external mapping app that can share GPS coordinates.

**Comment by Korb** [comment]
> Sounds like you might prefer the UI in **FakeTraveler**

Yes, thank you, this is a great app! ❤
