### ISSUE TITLE
Hope it can Granted adb permissions

### ISSUE THREAD

**Issue by Pantyhose-X** [warren-bank/Android-Mock-Location#6]
Does not run in adb mode, he has no effect at all

**Comment by warren-bank** [comment]
I have no idea what you're asking.. could you please give me a bash script to illustrate what you're trying to do?

**Comment by Pantyhose-X** [comment]
> I have no idea what you're asking.. could you please give me a bash script to illustrate what you're trying to do?

I just hope it can be like [Android-Locale-Changer](https://github.com/warren-bank/Android-Locale-Changer). 
Granted by command-line:
adb permissions

**Comment by warren-bank** [comment]
I haven't tried this.. but I just did a super quick google and the first result for me was [this forum](https://automagic4android.com/forum/viewtopic.php?t=8529) where the discussion is about ways to grant permissions to a particular app over an adb connection.

For [the permissions](https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.01.08/android-studio-project/Mock-my-GPS/src/main/AndroidManifest.xml#L7) required by this app, you might want to try the following:
```bash
adb shell pm grant "com.github.warren_bank.mock_location" "android.permission.ACCESS_MOCK_LOCATION"
adb shell pm grant "com.github.warren_bank.mock_location" "android.permission.ACCESS_COARSE_LOCATION"
adb shell pm grant "com.github.warren_bank.mock_location" "android.permission.ACCESS_FINE_LOCATION"
adb shell pm grant "com.github.warren_bank.mock_location" "android.permission.SYSTEM_ALERT_WINDOW"
adb shell pm grant "com.github.warren_bank.mock_location" "android.permission.FOREGROUND_SERVICE"
```

**Comment by warren-bank** [comment]
PS: regarding [Android-Locale-Changer](https://github.com/warren-bank/Android-Locale-Changer/blob/v1.1.0/android-studio-project/Locale-Changer/src/main/AndroidManifest.xml#L6)..

```bash
adb shell pm grant "com.github.warren_bank.locale_changer" "android.permission.CHANGE_CONFIGURATION"
```

**Comment by warren-bank** [comment]
to check for granted permissions, try:

```bash
adb shell dumpsys package "com.github.warren_bank.mock_location"
adb shell dumpsys package "com.github.warren_bank.locale_changer"
```

**Comment by Pantyhose-X** [comment]
Thank you for your application Awesome [AuroraDroid](https://gitlab.com/AuroraOSS/auroradroid) or [F-Droid](https://f-droid.org/en/) release
